### ISSUE TITLE
Unable to import package using PackageManager in Unity 2019

### ISSUE THREAD

**Issue by DanielEverland** [jeffcampbellmakesgames/unity-package-tools#1]
When adding `"com.jeffcampbellmakesgames.packagetools" : "https://github.com/jeffcampbellmakesgames/unity-package-tools.git#release/stable"`to my dependencies causes Unity to log a bunch of errors
![](https://i.imgur.com/5wr8UcZ.png)

You can see the full Editor log here: https://gist.github.com/DanielEverland/1aa27477df754a07aafcd3cb781f0b86

**Comment by DanielEverland** [comment]
Specific version is 2019.1.0f2

**Comment by jeffcampbellmakesgames** [comment]
Thanks for the report, I have been meaning to retest/update this tool based on the Package Manager changes in 2019.1 since it was recently released. I will retest this on ` 2019.1.0f2` and get back to you either later today or tomorrow.

**Comment by jeffcampbellmakesgames** [comment]
I just tried this on an empty 2019.10f2 project and everything seems to be working fine. I wonder though since I reread my readme and realized I did not have a comma `,` at the end of that example Json snippet; is there a comma at the end of the entry that you placed in your `manifest.json` file? That would certainly cause an issue with the Json not being valid.

For reference, this is what my initial manifest Json looks like  
```
{
  "dependencies": {
    "com.jeffcampbellmakesgames.packagetools": "https://github.com/jeffcampbellmakesgames/unity-package-tools.git#release/stable",
    "com.unity.package-manager-ui": "2.1.2",
    "com.unity.textmeshpro": "2.0.0",
    "com.unity.timeline": "1.0.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }  
}
```

**Comment by DanielEverland** [comment]
Silly me, I should've spotted that myself. That did indeed fix it 🤦‍♂️
